name: 'Documentation Generator'
description: 'Generate documentation for the EagleTRT team'
author: "eagletrt"
inputs:
  author:
    description: 'Documentation author'
    default: 'EagleTRT Team'
    required: false  
  project:
    description: 'Documentation project name'
    default: 'EagleTRT project'
    required: true
  folders: 
    description: 'The folders of the files that you want to document'
    default: '../utils'
    required: true
  
runs:
  using: 'node12'
  main: 'start.js'
branding:
  icon: 'arrow-up-circle'
  color: 'green'
