
name: Documentation
on: [push]


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Documentation
      uses: eagletrt/documentation@main
      with:
        author: Eagletrt
        project: Eagletrt Project
        rootfile: Title
        folders: ../utils/config_parser ../main.c
        version: 1.0.0
        release: 1.0.0
        language: c
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@4.0.0
      with:
        nojekyll: true 
        branch: docs # The branch the action should deploy to.
        folder: docs/_build # The folder the action should deploy.
